### ISSUE TITLE
A hint

### ISSUE THREAD

**Issue by Runrioter** [eggjs/egg-cookies#7]
This repo is based on [pillarjs/cookies](https://github.com/pillarjs/cookies).
And It extends with an encrypt/decrypt function that can't be customized.
I think that pure cookie getter and setter are fine.
- if cookie is used for fetching session, this approach (https://github.com/koajs/session/pull/100) is ok.
- Or, any customized separate encrypt/decrypt function is used smoothly. It is not necessary to have a new options.

What do u think?

: ) Looking forward this PR((https://github.com/koajs/session/pull/100)  is merged

**Comment by atian25** [comment]
sorry, don't notify this, you should open issue at https://github.com/eggjs/egg/issues

cc @dead-horse
